### ISSUE TITLE
Seems the work based on sd1.4?

### ISSUE THREAD

**Issue by sunhaha123** [kaist-cvml/scribble-guided-diffusion#1]

**Comment by Jason-xin** [comment]
"sd_weights_path": "checkpoints/stable_diffusion/SD_input_conv_weight_bias.pth", 
        do you know how to get this model？

**Comment by Glanceyes** [comment]
Thanks for your attention to our project.

We conducted the experiments using both GLIGEN and SD 1.4, but we've only uploaded the codes for GLIGEN so far. 
We will upload the codes based on the diffusers framework soon.
