### ISSUE TITLE
where is sd_weights_path?

### ISSUE THREAD

**Issue by Jason-xin** [kaist-cvml/scribble-guided-diffusion#2]
"sd_weights_path": "checkpoints/stable_diffusion/SD_input_conv_weight_bias.pth", ???? excuse me?

**Comment by Glanceyes** [comment]
Hello, thanks for pointing this out.

I apologize for the oversight regarding the sd_weights_path. I will upload the missing file shortly and update the repository.
Once it's available, you'll be able to set the correct path.

Thank you for your patience.
